### ISSUE TITLE
"Issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by Urubu495** [Urubu495/eiyoushi-master-quiz#25]
### 概要
このアプリは管理栄養士国家試験の対策をサポートする学習支援アプリ。過去の試験問題を利用してユーザーに出題し、回答履歴を分析して苦手な科目を特定する。そして、苦手分野の問題を優先的に出題し、効率的な学習ができるようにする。

### 実装予定の機能
- [ ] 会員登録機能
- [ ] ログイン機能
- [ ] パスワード変更機能
- [ ] メールアドレス変更機能
- [ ] ユーザー名変更機能
- [ ] 問題出題機能
- [ ] 回答履歴確認機能
- [ ] 問題絞り込み機能
- [ ] コメント書き込み機能
- [ ] 問題保存機能(後で復習したい問題などを保存する)
- [ ] 分野別の正答率確認機能(ユーザー全体の正答率も確認できるようにする)

### 必要なページ
- [ ] ホーム画面
- [ ] メニューバー
- [ ] ユーザー登録画面
- [ ] ログイン画面
- [ ] パスワード再設定画面
- [ ] メールアドレス再設定画面
- [ ] ユーザー名変更画面
- [ ] 問題出題設定画面
- [ ] 問題出題画面
- [ ] 問題出題画面(正解、不正解の場合)
- [ ] 問題出題画面(保存問題一覧、解答履歴一覧へ戻るページがある場合)
- [ ] 全ての問題回答後の画面
- [ ] 保存問題一覧画面
- [ ] 回答履歴一覧画面
- [ ] 分野別正答率画面
- [ ] 利用規約
- [ ] プライバシーポリシー
- [ ] サポート/ヘルプ

### リリース後に追加予定の機能
- [ ] 問題一覧確認機能
- [ ] 大項目別の正答率確認機能

**Comment by tarakish** [comment]
個人開発におけるプロジェクトマネジメントで作成したGitHubProjectをpublicに変更後、GitHubProjectのURLの提出もお願いしたいです。
また提出されたURLが少し誤っていたようなので再提出の際はご注意いただければです！

**Comment by tarakish** [comment]
提出はこのIssueのURLで大丈夫です（初回提出時は https://github.com/Urubu495/Portfolio/issues/25/issues と余計な/issuesという文字が含まれていたので気をつけていただければ大丈夫です！）
一度お返しするので正しいURLでご提出をお願いします。

**Comment by Urubu495** [comment]
提出URLの方、間違っており、失礼いたしました！
レビュー依頼、再提出致しましたので確認お願いします！

**Comment by Tsuchiya2** [comment]
Projectsにアクセスしましたが、看板・issue・ストーリーポイントの確認ができませんでした。
カリキュラムをご確認いただき、上記確認できる状態で再提出をお願いいたします。

<img width="595" alt="image" src="https://github.com/Urubu495/Portfolio/assets/61481161/427fa510-f9f9-4dde-960d-dd2ef4f5e251">

**Comment by Urubu495** [comment]
すみませんProjects追加しました。

**Comment by Tsuchiya2** [comment]
閲覧可能なのを確認しました。
カリキュラムにストーリーポイントの付け方が書いてあったかと思うのでご確認ください。
また、ストーリーポイント５以上のものは見通しが不鮮明なissueかと見受けられたので、ストーリーポイント1,2になるまで細かくissueを細分化しましょう。細分化することで進捗を実感しながら実装を進められますし、何が分かっていて何が分かっていないのかが可視化させるので対応をお願いします。

**Comment by Urubu495** [comment]
ストーリーポイントを1,2までに分割するのは難しかった為、ストーリーポイントが5以上にならないようにIssueを細分化しました。確認お願いします。

**Comment by busitora** [comment]
LGTM!
